version: '3'

services:
  shiny:
    build:
      context: .
      dockerfile: r/Dockerfile
    image: nachthimmel/shiny:latest
    container_name: shiny_app
    ports:
      - "3838:3838" 
    volumes:
      - ./r/Shiny_Gantrisch:/srv/shiny-server
      - ./python:/srv/shiny-server/python  # Volume-Mount für den Python-Ordner

  python:
    build:
      context: .
      dockerfile: python/Dockerfile
    image: nachthimmel/python:latest
    container_name: python_tess_ida
    volumes:
      - ./python:/app/python
      - ./data:/app/data
